### ISSUE TITLE
Issues with low sample rate audio

### ISSUE THREAD

**Issue by Cuzziwuzzi** [Miloet/TheManyModsOfLethalCompany#12]
It seems audio files with low sample rates introduce significant artifacting when played back in-game. (files and video attached)

On a (probably) unrelated note, the loop function doesn't work correctly. There is a small cut before a track fully loops

https://github.com/user-attachments/assets/20371a65-3317-45ea-9759-799f2ff44795

[audio.zip](https://github.com/user-attachments/files/16568828/audio.zip)

**Comment by Miloet** [comment]
Thank you for your report. I'll look into it!

**Comment by Miloet** [comment]
I fixed the looping issue but the compression issue is a bit more involved on your part. The way I found to fix it is to use a .wav file instead of .mp3 as .wav is uncompressed, thus I added .wav compatibility with the mod. It's a unity loading issue that causes the artifacts so this is the most I can do on my end. I recommend converting whatever files you were using to .wav and using them instead of the .mp3's
