### ISSUE TITLE
CruiserTunesExampleAddon Problem

### ISSUE THREAD

**Issue by wman3** [Miloet/TheManyModsOfLethalCompany#13]
Wasn't sure where else to raise this issue but the format in the [example mod](https://thunderstore.io/c/lethal-company/p/Mellowdy/CruiserTunesExampleAddon/) for creating your own doesn't work. The file path in the example mod is _...addon\Customsongs\songs_ but that doesn't work. It only works when it is _...addon\plugins\Customsongs\songs_ as I found out when making one myself. Don't know why but I found someone else did it that way and the songs started loading. Just wanted to let ya know.

**Comment by Miloet** [comment]
I'll look into it.

Edit: ok yeah this isn't something I can fix from the mod side so the mods that don't use the Plugins/CustomSongs method are sadly broken unless manually fixed or manually downloaded. However I did change the original to use the method so that others in the future will as well. In the end it was thunderstore messing things up T-T
