### ISSUE TITLE
You can't purchase the mini-fridge at all times as it is on a store rotation.

### ISSUE THREAD

**Issue by SpazzMaticus107** [Miloet/TheManyModsOfLethalCompany#14]
It doesn't show up in the store and if you try to buy it anyway by typing in "mini-fridge", "minifridge, "fridge", "mini" the terminal will say that the item is out of stock.

Ok I uninstalled all the other mods and my best guess is that this item is on a store rotation (just like costumes, the shower and the other stuff) which means you can only buy it when you get the chance.

**Comment by Miloet** [comment]
That is correct, it is a cosmetic item in rotation with the others. I'll see if I cant make a setting to allow the user to change it into a ship upgrade instead, making it always available. Otherwise, you could use any of the mods that allows the purchase of any decoration, ignoring the rotation problem.

**Comment by SpazzMaticus107** [comment]
Alright then. Thanks
